### ISSUE TITLE
SOauto test failing? 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#10]
The test for SOauto is failing but I don't know how to fix it.

**Comment by mdsumner** [comment]
It's the plot matching by vdiffr afaics

**Comment by Maschette** [comment]
So how do I fix it? do I need to fix the plot or the test?

**Comment by Maschette** [comment]
Oh I just realised this will be my fault as when I made it flexible for point/line characteristics I changed the default point color. I will have to work out how to update the .svg

**Comment by mdsumner** [comment]
I was expecting to do it myself, what you do is run

```R
vdiffr::manage_cases()
```

and a shiny app walks you through it. I'm still learning

**Comment by Maschette** [comment]
fixed it.
