### ISSUE TITLE
Repeated application of SObin gets out of whack

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#110]
```
SOmap_auto()
pts <- cbind(lon = runif(1e6, min = -180, max = 180), lat = runif(1e6, min = -90, max = 90))
SObin(pts[, 1], pts[, 2])
```
then call `SObin(pts[, 1], pts[, 2])` again, it gets plotted with a slightly larger plot region, then call it again and it gets plotted using the entire graphics viewport

**Comment by raymondben** [comment]
The issue lies with raster::plot I think. This causes similar but slightly different behaviour:
```
mymap <- SOmap_auto()
pts <- cbind(lon = runif(1e6, min = -180, max = 180), lat = runif(1e6, min = -90, max = 90))
b <- SObin(pts[, 1], pts[, 2], add = FALSE)
plot(mymap)
SOplot(b)
SOplot(b)
```

**Comment by mdsumner** [comment]
should be fixed by using `terra::image()` in place of `raster::plot()`

**Comment by Maschette** [comment]
noting this was changed in https://github.com/AustralianAntarcticDivision/SOmap/commits/main/R/SObin.R 

A quick test using: 
````
library(SOmap)
pts <- cbind(lon = runif(1e6, min = -180, max = 90), lat = runif(1e6, min = -90, max = -20))
b <- SObin(pts[, 1], pts[, 2], add = FALSE)

mymap <- SOmap_auto(b)
plot(mymap)
image(b, add = TRUE)
SObin(pts[, 1], pts[, 2], add = TRUE)
plot(b, add=TRUE)
````

I think this can be closed now
