### ISSUE TITLE
Add VME locations. 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#2]
Add an option to load the Registered VME and VME risk areas and small scale VME rectangles as a function option. Give option for 1 nm radius buffer around the registered and risk area points.

**Comment by raymondben** [comment]
VME data is visible through gis.ccamlr.org but not downloadable as far as I can see

**Comment by Maschette** [comment]
Yep I am going to speak to them about it at lunch.

**Comment by raymondben** [comment]
Note that I've only added the registered VME polygons so far (because I forgot which other ones were needed). The risk areas and small-scale rectangles are ready to go though, so I'll add them too.
