### ISSUE TITLE
Hiding stuff behind the mask doesn't always work

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#20]
See e.g.
```
SOmap2(Trim = -45, IWC = TRUE, IWClab = TRUE, Grats = TRUE, fronts = TRUE)
```
there is a front line visible way beyond the map extent - perhaps we can trim these rather than relying on the mask to hide them?

**Comment by Maschette** [comment]
Yep; this was done when we didn’t know a nice way to crop them. We could implement similar code to that used for land to do the same thing.

**Comment by Maschette** [comment]
I think I have fixed this, I used the same cropping as done for land. I am contemplating turning it into a broad internal cropping function to make the code a bit neater. 

It would also be worth adding "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0" to SOmap_data so we don't have to run projection(SOmap_data$continent) everytime.

**Comment by Maschette** [comment]
Hard no on my cropping, the class of the continent layer is "SpatialPolygonsDataFrame" whilst the fronts are "SpatialLinesDataFrame"

**Comment by Maschette** [comment]
Wait I worked it out, you don't use sf::st_buffer and then it works fine.
