### ISSUE TITLE
ggplotting

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#24]
Just a placeholder for notes:
- need to think about adding ggplot code to object layers in the same way that `plotfun`/`plotargs` hold the code needed for base plotting

**Comment by Maschette** [comment]
Hey @raymondben just checking, the SOgg function will currently print the base map for everything except the legend? and then I notice the code has some of the layers in it, are these working too?

**Comment by raymondben** [comment]
Yeah, I didn't get around to some layers at the time (SSRU/SSMU/CCAMLR/SPRFMO/RB). I will get back to this, including the note above (i.e. `SOgg` will convert a `SOmap` object that uses base/raster plotting calls to an object that uses `ggplot` calls; the `print` and `plot` methods for that new object will then evaluate those calls and return an actual `ggplot` object, which can then be displayed using the usual `print.ggplot` method)

**Comment by Maschette** [comment]
So I have everything working except for: SSMUlabs (see other issue), Domainslab, IWC and IWClab. 

Also the more I think about it the more I am unsure about making SOauto_map on ggplot but thats a different days issue.

**Comment by raymondben** [comment]
SSMUlabs, Domainslab, IWC, IWClab now working, sorta. Probably need to revisit all of the ggplotting code as things evolve but for now probably ok

**Comment by Maschette** [comment]
Can we close this now @raymondben?

**Comment by raymondben** [comment]
closing this, it's just a general gg-related placeholder for which we now have some more specific tasks (and no doubt more to come)
