### ISSUE TITLE
SOmap() not working with par(mfcol)

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#28]
Any tips on this? when you run:
```
par(mfcol=c(1,2))
SOmap()
SOmap()
```
to get side by side maps it plots the first but not the second and if you try and use SOplot or SOleg with either of them they do not appear.

**Comment by mdsumner** [comment]
It works if the par is done in one big hit, i.e. I remove the `op <- par(mar = rep(0.01, 4), oma= rep(0.0, 4), mai= rep(0.0, 4))` line from print.SOmap and then run

```R
a <- SOmap()
op <- par(mar = rep(0.01, 4), oma= rep(0.0, 4), mai= rep(0.0, 4), mfrow = c(2, 2))
a
a
a
a
```

and all is well. So, I guess we need some kind of handler, which provides the defaults we use and *adds* any other parameters, and perhaps we restrict what they can be? 

```R
## you are in control now ...
SOpars(mfrow = c(2, 2)))
a
a
a
a
#graphics.off()
```

I'm out of my depth a bit

**Comment by raymondben** [comment]
Not quite sure what's going on either, but it seems to be the `oma` part of the `par` call that's the issue. If the line in `print.SOmap` is altered to just `op <- par(mar = rep(0.01, 4), mai = rep(0.0, 4))` then the mfcol as per Dale's original method seems to work ok.

**Comment by Maschette** [comment]
One option would to be to record the base settings of par() in the print method and if they dont match when you print dont set any par settings. if they do match then it can do what it currently does. This could work for SOauto_map as well

**Comment by Maschette** [comment]
The oma thing makes a lot of sense as when you use mfcol or mfrow it is happy to have internal figure margins etc specified for each plot but from the reading on par i was just doing if any of them try to specify oma then it fails. So: 

a<-SOmap()
par(mfcol=c(2,1), oma=rep(0.0, 4))
a
par(mar=c(3,4,2,4))
a

would work (except we overwrite mar internally atm so it wouldn't actually) but if you had oma in the second par it would not.

**Comment by raymondben** [comment]
I guess since `oma` is the outer margins (around *all* of the subplots) then you can only specify it for a new plot (new page), and not for subsequent subplots on the same page?
If you wanted to re-add the `oma` spec, just check `par()$page` first. If it's `TRUE`, the next plot is going to a new page so you can set `oma`. If it's `FALSE`, it's not, and you can't. I think.

**Comment by mdsumner** [comment]
oh w00t that sounds right

**Comment by Maschette** [comment]
We also need to work out how to do this for SOauto_map. Which is a different issue as it's not an OMA issue, I think it is a new=FALSE in aspectplot.default

**Comment by raymondben** [comment]
looks like the remaining part of this issue is the aspectplot.default behaviour (prev comment): @mdsumner, all yours

**Comment by Maschette** [comment]
This may be fixed with your latest changes @raymondben?
