### ISSUE TITLE
Fix bathyleg overplotting when using small(ish) image sizes. 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#29]

**Comment by raymondben** [comment]
You can tweak the `plotargs` in a `SOmap` object directly. As yet none of this is documented, because (amongst other reasons) none of it is final and therefore may change. But something like:
```
p <- SOmap()
p$bathy_legend$plotargs$labels$adj <- 0
p
```
or whatever parm you need to tweak.

**Comment by Maschette** [comment]
Yep this is me being an idiot and forgetting things exist. I will leave this issue up to remind myself to write some documentation
