### ISSUE TITLE
Stupid dateline. 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#30]
Nicer title than I was going to put. SOauto_map doesn't seem to handle having two points either side of the date line and doing its thing. 

```
#Look at these lovely points in the Ross Sea. 
SOauto_map(x=c(-175, 180), y=c(-50, -65))
#oh wait... I have the hole continent.... 
```
![image](https://user-images.githubusercontent.com/14663215/55132296-fda54100-5175-11e9-9dc0-4408b8d05e09.png)

**Comment by mdsumner** [comment]
Ok ok I hear ye

**Comment by Maschette** [comment]
I'm not sure I see a simple automatic solution to this without something like reverse=TRUE to essentially take the opposite range of the one you have; so if you have -175, 175 with reverse=TRUE is takes -175 -> -180 and 180 -> 175 and joins them. I'm just not sure how to code it nicely.

**Comment by mdsumner** [comment]
Nah, working in longlat as Cartesian is a no good - I've rejigged to calculate the centre in geocentric coordinates, just doing some checks ...

**Comment by mdsumner** [comment]
Try now!

``` r
library(SOmap); SOauto_map(x=c(-175, 180), y=c(-50, -65)); SOauto_map(x=c(-175, 180), y=c(-50, -65), trim_background = F)
#> Loading required package: raster
#> Loading required package: sp
```

![](https://i.imgur.com/xgAyloF.png)![](https://i.imgur.com/QVLUFlx.png)

<sup>Created on 2019-03-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Maschette** [comment]
`Error in proj4::ptransform(x, source, target, ...) :  major axis or radius = 0 or not given `

**Comment by Maschette** [comment]
As a test I tried this: 
```
SOmap:::mid_point(dat$lon,dat$lat)
 Show Traceback
 
 Rerun with Debug
 Error in UseMethod("reproj") : 
  no applicable method for 'reproj' applied to an object of class "c('double', 'numeric')"
```

**Comment by mdsumner** [comment]
Reinstall and try now (the error is missing datum parameters on the PROJ string, which is platform-dependent). 

That last thing should be
```R
SOmap:::mid_point(cbind(dat$lon,dat$lat))

```
