### ISSUE TITLE
SOauto limits

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#4]
Add  xlim & ylim options for SOauto. This is super easy I just dont have the current version cloned to my machine but it will be something along the lines of (in line 66) :   
`if (is.null(xlim)){
  xlim <- range(x, na.rm = TRUE)} ## Add checks for centerlines being = to center xlim range and x being within xlim range. 
  
  if (is.null(ylim)){
  ylim <- range(y, na.rm = TRUE)}`

But as the comment says you will want to add checks and warnings if the x and y ranges are outside the limits and if centre_lon = NULL, centre_lat = NULL are not NULL and no equal to the center of the limits than stop and throw a warning. 

Also I think we are almost at the point of removing the auto data generation and allowing x and y to be null if there is an xlim ylim supplies. 

Ok Bed time

**Comment by mdsumner** [comment]
what about set x, y to the range and input_lines = F, input_points = F ?


I agree it could be better but I think that gives more or less the same
