### ISSUE TITLE
SOauto_map hating on rasters

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#42]
``` r
library(SOmap)
#> Loading required package: raster
#> Warning: package 'raster' was built under R version 3.5.3
#> Loading required package: sp
SOauto_map(x=ice, gratpos = c("left", "top"))
#> Warning in SOauto_map(x = ice, gratpos = c("left", "top")): input 'x'
#> is a raster, converting to an extent for a simple plot of input_points/
#> input_lines
```

![](https://i.imgur.com/QEXJq8k.png)

<sup>Created on 2019-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mdsumner** [comment]
So after looking at this, I agree - it is hating on  rasters!  

What do you think it should do? I think it should plot the raster, use the raster for the structure as the **target** background grid.

**Comment by mdsumner** [comment]
Better now

``` r
library(SOmap)

SOauto_map(x=ice, gratpos = c("left", "top"))
SOplot(ice, col = palr::icePal(100))
```

![](https://i.imgur.com/AZgoFP8.png)

<sup>Created on 2019-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
