### ISSUE TITLE
automap wackiness

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#46]
1. `SOauto_map(c(-122, 20), c(-78, -50))` crops the map to such an extent that it doesn't show the given points

`SOauto_map(c(-122, 20), c(-78, -50), pcol = "red")` does not

2. Similarly,
```
xy <- expand.grid(x = -120:20, y = -70:-50)
SOauto_map(xy[,1], xy[,2])
```
crops the map too much, but
```
SOauto_map(xy[,1], xy[,2], trim_background = FALSE)
```
does not.
I think that the line
```
      target <- crop(target, extent(rgdal::project(cbind(xlim, ylim), prj)))
```
is cropping too zealously, because it's only using the two corners of the (lat-lon) extent.
Does:
```
      target <- crop(target, extent(rgdal::project(cbind(x, y), prj)))
```
make more sense?

**Comment by mdsumner** [comment]
I don't see the difference in the 1. alternatives? 

You are right this is screwed, I'll see if a quick fix helps but I was refactoring this

**Comment by Maschette** [comment]
I think this is an RStudio plot issue, I had i but then saved an image as a jpg and it was fine.

**Comment by raymondben** [comment]
Ignore number 1, I can't reproduce it now. Maybe it was a result of an odd graphics device state.

**Comment by mdsumner** [comment]
New scheme in branch

**Comment by mdsumner** [comment]
... it's only the internals, to give a target and xy (may be NULL) from various inputs - will smooth out SOauto_map in the branch

**Comment by mdsumner** [comment]
Now in https://github.com/AustralianAntarcticDivision/SOmap/pull/48

``` r
  library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
  SOauto_map(c(-122, 20), c(-78, -50)) 
```

![](https://i.imgur.com/RzZKyLz.png)

``` r

SOauto_map(c(-122, 20), c(-78, -50), pcol = "red")
```

![](https://i.imgur.com/9mFiN9O.png)

``` r

xy <- expand.grid(x = -120:20, y = -70:-50)
SOauto_map(xy[,1], xy[,2])
```

![](https://i.imgur.com/TjNIohZ.png)

``` r

SOauto_map(xy[,1], xy[,2], trim_background = FALSE)
```

![](https://i.imgur.com/FDRhb2w.png)

<sup>Created on 2019-06-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Maschette** [comment]
Not sure if I should put it here or make a new issue for new auto_map comments. Ill go here for now. 

When I plot SOauto_map(c(160, -160), c(-50, -75)) i get this image in the window, but if i use reprex it works... 

![image](https://user-images.githubusercontent.com/14663215/58758047-fecd6280-8558-11e9-91bc-22dc446e3527.png)


``` r
library(SOmap)
SOauto_map(c(160, -160), c(-50, -75))
```

![](https://i.imgur.com/yqXXPb1.png)

<sup>Created on 2019-06-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by raymondben** [comment]
I think these are all resolved now in the dev branch
