### ISSUE TITLE
Package dependency versions

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#49]
So we have a number of package dependencies such as reproj and spex which rely on the dev versions rather than the ones on cran. In my head this is not ideal, it makes it harder for people to install or update the package.

**Comment by mdsumner** [comment]
Needs the Remotes field set is all, will fix

**Comment by mdsumner** [comment]
Fixed, both updated on CRAN https://github.com/AustralianAntarcticDivision/SOmap/commit/6d10522cb657c8331ff758e7b90187626044ae3e
