### ISSUE TITLE
Release 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#53]
Just checking, are we thinking we are at a stable version? 
Should we be making a release so that people installing can always have a stable version if we start to mess with things again?
Main reason being I’m about to use this at CCAMLR and people may want to install it and ben is going to teach it at a course.

**Comment by raymondben** [comment]
I think you still need to:
- [ ] update NEWS with any further notable items
- [ ] confirm that everything is working as expected
- [ ] probably other things I've forgotten
