### ISSUE TITLE
White space on SOmap_auto

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#57]
SOmap_auto() margins do not seem to work properly (at least on mine and Bens machines) giving very large white margins.

**Comment by Maschette** [comment]
So i have tracked the issue to this line https://github.com/AustralianAntarcticDivision/SOmap/blob/ca946afc48b59562b3e70b94c48ccb261d0699e0/R/SOmap_auto.R#L299 

which calculates where the sideways figure margins should be in aspect plot (black box). It is not doing it correctly, especially when doing thin plots, so you end up with a heap of white space. I'm not sure what the fix is though. 

![image](https://user-images.githubusercontent.com/14663215/62503462-a99f1d00-b837-11e9-939a-a43bd754a249.png)

![image](https://user-images.githubusercontent.com/14663215/62503509-d3f0da80-b837-11e9-8138-4b94b0867151.png)

**Comment by Maschette** [comment]
Until we can work out a decent solution I have a branch with a possible solution which looks at the r value and works on coming in from 0 and 1 rather than going out from 0.5. It seems to work more consistently. I had to add a third option for when r is between 0.6 - 1.5 (mostly square). 

I do feel like there is definitely a better way to do it but I can't think of it at the moment. 

There is a branch I am working on if you want to look.

**Comment by mdsumner** [comment]
We need an example that actually catches it in the act, for instance when I *first* ran this I didn't get any data to the east or west, but then subsequent plot made it work. Do you still see graticule labels out in the wilderness when you encounter this? 


```R
library(SOmap)
xy <- structure(c(-113.300354107545, 24.9787320169671, 35.9360014796499, 
            -82.7115267060765, 88.9969743360287, -30.9080025684759, -30.3827639909707, 
            -47.227441042256, -41.347957269103, -52.4722832243627), .Dim = c(5L, 
                                                                             2L))

SOmap_auto(xy)

```

**Comment by mdsumner** [comment]
Urm, no what I thought was your problem was not right.  I might have it

**Comment by raymondben** [comment]
@mdsumner try this for the need-to-plot-twice thing:

```
ma <- SOmap_auto(x = c(-277.8, -107.2, -35.1, -193.6, -321.9), y = c(-64.5, -42.2, -61.5, -53.7, -49.8), bathyleg = FALSE)
plot(ma)

ma <- SOmap_auto(x = c(-280.5, -12.8, -98.1, -246.6, -227.0), y = c(-63.8, -56.2, -64.0, -41.4, -40.6), bathyleg = FALSE)
plot(ma) ## cropped margins
plot(ma) ## all good
```

**Comment by raymondben** [comment]
OK, clipping should be fixed in https://github.com/AustralianAntarcticDivision/SOmap/commit/1b7c9d28d08089337504bcc6d3d378c4fe240171

**Comment by raymondben** [comment]
Crazy whitespace example:
```
ma <- SOmap_auto(x = c(-36.4, -175.1, -125.3, -116.7, -82.8), y = c(-38.4, -38.4, -44.2, -63.1, -46.0), bathyleg = FALSE)
plot(ma)
```

**Comment by raymondben** [comment]
https://github.com/AustralianAntarcticDivision/SOmap/commit/498ff40411845298674a825f77b31f8a74f024d3. @mdsumner @Maschette is this any better?

**Comment by raymondben** [comment]
Assuming it's ok
