### ISSUE TITLE
still plotting when nullifying required fields (bathymetry)

### ISSUE THREAD

**Issue by grwhumphries** [AustralianAntarcticDivision/SOmap#63]
**Describe the bug**
When trying to get an SOmap() object to NOT plot (as an example in a course) by nullifying the bathymetry field, if there is an existing plot in the plot window, it will still plot. 

**To Reproduce**
```
mymap <- SOmap()
temp <- mymap
temp$coastline <- NULL
temp$ice <- NULL
plot(temp)
```
The above produces 
![image](https://user-images.githubusercontent.com/1613298/64259017-8c3d9b80-cf28-11e9-9c13-394bd18e2966.png)

If you continue with that object in the plot window and type in the console:  
```
temp <- mymap
temp$bathy <- NULL
plot(temp)
```
Instead of getting an expected error, you get:  
![image](https://user-images.githubusercontent.com/1613298/64259138-ce66dd00-cf28-11e9-9e10-8255742189d6.png)

Seems like if there's an existing plot in the plotting window, it just plots anyways.

**Comment by raymondben** [comment]
Ahahahaha. Yes, you are right. The plotting code uses the `bathy` layer to set up a new plot in the graphics device. If the `bathy` layer is missing BUT there is an existing plot, then it just plots over the top. If there was no existing plot, it'd throw an error.
I've updated the explanation and added an example of plotting without showing any bathymetry, just by setting the raster values to `NA` (thanks to @Maschette for pointing that one out). https://github.com/SCAR/EGABIcourse19/commit/6d47789bf7af1372ae3adf2649fedd8b3cdbe802
