### ISSUE TITLE
Wanted: Space for legend

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#64]
So there is a use case where you may want to not have the curved bathy legend: 
`SOmap(bathy_leg=FALSE)` but you want to use `SOleg()` this becomes an issue as the space where `SOleg()` normally plots in the left over area from bathy_leg.

**Comment by raymondben** [comment]
One option is to add another parameter to `SOmap` to allow space to be left for the legend but no legend plotted. But this creates a bit of a conflict between this parameter and the existing `bathy_legend` parameter.
An alternative could be to provide a function to merge the `SOmap_legend` object with the `SOmap` object. The merge function adds the extra space if required. This same merge functionality has already been raised, see https://github.com/AustralianAntarcticDivision/SOmap/issues/45. (I think this is the better approach.)
In the meantime a workaround is to do `SOmap(..., bathy_legend = TRUE)` then delete the legend component from the returned `SOmap` object - the EGABI course notes give an example of this (https://scar.github.io/EGABIcourse19/mapping.html#somap).

**Comment by raymondben** [comment]
@Maschette what if we keep just to the `bathy_legend` parameter but allow it to take a third value, so it can be `TRUE`, `FALSE`, or `"space"` (or `"empty"` or something like that). The third option will leave the space but not plot the legend. I don't think that will cause conflicts with the merge functionalilty, if/when we get to that

**Comment by Maschette** [comment]
Could potentially go with NULL where it then leaves the white space but doesnt plot anything.

**Comment by raymondben** [comment]
ok

**Comment by raymondben** [comment]
https://github.com/AustralianAntarcticDivision/SOmap/commit/48c17dce6f2951839546394d52eed1c190e7463f
