### ISSUE TITLE
Broken graticules

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#66]
The latest version of the graticules package breaks the border and the legends. 

``` r
library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
SOmap()
#> Warning in .pointsToMatrix(p2): longitude > 180 (times about 300)

```

![](https://i.imgur.com/X0u8h5s.png)

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment]
good one thanks!  Please re-install from github

```R
remotes::install_github("mdsumner/graticule")
```

**Comment by Maschette** [comment]
Thanks Mike, I wasn't sure where best to report it. That fixed it.

**Comment by mdsumner** [comment]
Definitely a good one!  A classic off-by-one 2x ...

**Comment by Maschette** [comment]
just as a note, you still get the `> Warning in .pointsToMatrix(p2): longitude > 180 (times about 300)`
warnings for SOmap() internally caused by bticks. For the minute I have thrown a `suppressWarnings()` around it atm but could be worth putting in the graticule function :)

**Comment by Maschette** [comment]
argh i didn't actually fix it, I will try and find in graticule which bit it is.

**Comment by mdsumner** [comment]
You could make SOmap create the lines in -180/180: 

```R
xx <- c(-180, -135,  -90,  -45, 0, 45, 90, 135, 180)
yy <- c(seq(from = -90, to = -45, by = 15), -45)
library(SOmap)
grat <- graticule::graticule(xx, yy, proj = raster::projection(Bathy))

```

I think the warning is ok, I'm a bit reluctant to suppress it.

**Comment by Maschette** [comment]
Working 0 - 360 is kind of how we do most things internally, I think I will just have to suppress them all at the moment. My suggestion for the graticules package would be to suppress the warnings but put an if statement that gives a single warning if the graticule is greater than 180 as in some instances you end up with about 120 warnings.

**Comment by mdsumner** [comment]
I changed my mind and will zap the warnings in graticule. They come from geosphere::distRhumb

**Comment by Maschette** [comment]
I'm pretty sure this has been fixed now yes?

**Comment by mdsumner** [comment]
yep
