### ISSUE TITLE
Points added after a raster layer is added are incorrectly projected

### ISSUE THREAD

**Issue by ryanreisinger** [AustralianAntarcticDivision/SOmap#67]
Adding points to a SOmap_auto plots the points in the correct place. However, adding points after a raster layer has been added to the SOmap_auto, plots the points incorrectly.

```
library(raster)
library(SOmap)

r <- raster(res = 0.1, xmn = -10, xmx = 70, ymn = -75, ymx = -30, crs = "+proj=longlat +datum=WGS84")
values(r) <- runif(ncell(r))

islands <- data.frame(x = c(37.743611, 37.943333), y = c(-46.9125, -46.644167))
    
# Plot the raster then the points (plot01.png)
plot(SOmap_auto(r))
SOplot(r)
SOplot(islands$x, islands$y)

# Compare with plotting just the points (plot02.png)
plot(SOmap_auto(r))
SOplot(islands$x, islands$y)
```
plot01.png (adding points after raster):
![plot01](https://user-images.githubusercontent.com/13516646/67571859-45547100-f735-11e9-842a-4987dbf9d215.png)

plot02.png (adding points without adding the raster):
![plot02](https://user-images.githubusercontent.com/13516646/67571879-5309f680-f735-11e9-9284-7800979042d2.png)

An overlay of the two images, where you can see how the points have shifted:
![plot_blend](https://user-images.githubusercontent.com/13516646/67571910-63ba6c80-f735-11e9-806c-51a7b1c7f6f3.png)

The issue also occurs when a target projection is set explicitly at each step, and if the plots are plotted directly to file.

**Comment by ryanreisinger** [comment]
Perhaps related to #36, where order matters?

**Comment by Maschette** [comment]
I would almost certainly say so

**Comment by raymondben** [comment]
fixed https://github.com/AustralianAntarcticDivision/SOmap/commit/8ec00f85600cc260598447db66fe392410a457cc

**Comment by raymondben** [comment]
@ryanreisinger your example above works fine for me, points in the same spot in both cases. Can you check please that you're using the dev-0.6 branch? (This hasn't yet been merged into master) Otherwise I'll look again.

**Comment by ryanreisinger** [comment]
@raymondben , yes, I must have been using the master (version 0.5.2.9999) still.

**Comment by ryanreisinger** [comment]
@raymondben Now using dev-06 I can confirm the fix has solved the problem, thanks!

**Comment by raymondben** [comment]
Hooray!
