### ISSUE TITLE
Trim weirdness in SOmanagment

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#68]
Henrik nicely bought to my attention that SOmanagement(trim-55) doesn't work. I would have done a full reprex but my computer on the AAD network seems to be blocking imgur (classic aad). 

```
library(SOmap)
SOmap(trim = -55)
SOmanagement(ccamlr = TRUE, ccamlr_labels = TRUE, trim = -55)
```
![image](https://user-images.githubusercontent.com/14663215/69521284-b8f6d180-0fb2-11ea-87aa-278d9bc5e201.png)

I also tried this which works for SOmap_auto but it didnt work 
```
library(SOmap)
x<-SOmap(trim = -55)
x
SOmanagement(ccamlr = TRUE, ccamlr_labels = TRUE, trim = -55, basemap=x)
```
SOmanagement(ccamlr = TRUE,  trim = -55, basemap = x)
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In xy.coords(x, y, xlabel, ylabel, log) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
4: In plot.window(...) : "border" is not a graphical parameter
5: In plot.window(...) :
 Error in plot.window(...) : need finite 'ylim' values 
__

**Comment by raymondben** [comment]
WIP on branch dev-0.6

**Comment by raymondben** [comment]
https://github.com/AustralianAntarcticDivision/SOmap/commit/c245a379dd62aca321a4f82018898f50d466e456
