### ISSUE TITLE
Bad netcdf data with wrong extent

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDivision/SOmap#70]
This file `ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-SH50KMEASE2-200206-fv2.0.nc` from http://data.ceda.ac.uk/neodc/esacci/sea_ice/data/sea_ice_thickness/L3C/envisat/v2.0/SH/2002

comes in with the wrong extent, the units are in km. 

``` r
f <- "~/ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-SH50KMEASE2-200206-fv2.0.nc"
library(raster)
raster::raster(f, varname = "sea_ice_thickness")
class      : RasterLayer 
#> dimensions : 216, 216, 46656  (nrow, ncol, ncell)
#> resolution : 50, 50  (x, y)
#> extent     : -5400, 5400, -5400, 5400  (xmin, xmax, ymin, ymax)
#> crs        : +proj=laea +x_0=0 +y_0=0 +rf=298.257223563 +lat_0=-90 +lon_0=0 +a=6378137 
#> source     : /perm_storage/home/mdsumner/ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-SH50KMEASE2-200206-fv2.0.nc 
#> names      : thickness.of.the.sea.ice.layer 
#> z-value    : 1022889600 
#> zvar       : sea_ice_thickness
```

<sup>Created on 2020-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

A fix is to re-assign the extent * 1000 

(you might need to install the latest version of SOmap)

``` r
f <- "~/ESACCI-SEAICE-L3C-SITHICK-RA2_ENVISAT-SH50KMEASE2-200206-fv2.0.nc"
library(raster)
r <- raster::raster(f, varname = "sea_ice_thickness")
extent(r) <- extent(r) * 1000
library(SOmap)
SOmap()
SOplot(r)
```

![](https://i.imgur.com/mBwn2W4.png)

<sup>Created on 2020-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Maschette** [comment]
Is this a SOmap issue?

**Comment by mdsumner** [comment]
Not really, but there are implications - more to come

**Comment by raymondben** [comment]
@mdsumner more to come or can we close this?

**Comment by mdsumner** [comment]
Close, I think I fixed it
