### ISSUE TITLE
Wanted: make the park fronts in SOmap data

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#71]
The netCDF for the park fronts are in the package but the data as far as I can tell are not in SOmap_data. it would be good to get them added as a layer so users can call on them without having to call on a netcdf. We should also make them the default for fronts

**Comment by mdsumner** [comment]
OK   https://github.com/AustralianAntarcticDivision/SOmap/commit/1b67e4fc9b4bfddc549f879ecc909540bd5a3c6c

**Comment by raymondben** [comment]
Why the Park fronts by default? Is there some consensus that these are better to use than Orsi (or S&R or whatever we are using now)?

**Comment by Maschette** [comment]
We currently have orsi (1995) as default, Park is an updated version of the orsi fronts, I think we keep them both but have Park as the default as it is more realistic of current frontal locations than Orsi.

**Comment by raymondben** [comment]
They aren't exactly equivalent though - Orsi was based on profiles, Park from satellite altimetry I believe. And there are other contemporary estimates (Kim & Orsi / Chapman / Lovenduski / Sokolov & Rintoul is not that old either). So, yes, Park is more recent than Orsi but is also a depiction of different properties. Just suggesting that - unless you know of a consensus already - perhaps now is a good time to quiz a legit oceanographer as to which of the many options might be the best default, if we are going to change it.

**Comment by Maschette** [comment]
It was based on the fact I am working on 3 seperate papers with oceanographers who have told me that Orsi should be replaced with Park in all the things we are doing. I still think we should have both

**Comment by mdsumner** [comment]
But, there are consequences to changing a long-standing default in existing software. The *right* thing to do (from dev perspective) is add the option to choose the new data, but to keep the old default.  Consider that a new "better default" comes along, or someone finds a problem with the current default, it potentially keeps changing.

**Comment by Maschette** [comment]
Whilst generally I would agree, defaults do change and as long as they are documented I think it is fine. 
Considering how much I have head the phrase “Orsi should stop being used” recently I think having it as the default is somewhat silly. I will speak to some more oceanographers tomorrow and double check beyond the ones I have been working with.

**Comment by raymondben** [comment]
Before people get too used to this data set being available, can I suggest we rename it to something more specific (`park_fronts`, perhaps?). The generic `ACC_FRONTS` name may become confusing down the track if we add yet more alternative front data sets.

**Comment by Maschette** [comment]
Yep. I agree

**Comment by mdsumner** [comment]
6b9210c

**Comment by raymondben** [comment]
To do: change the handling of the `fronts` parm in `SOmap` so that will accept either logical or string. If logical and `TRUE`, show the Orsi fronts (for backwards compatibility). If it's a string it can be either "Orsi" or "Park" (or other options later, if we get carried away).

**Comment by Maschette** [comment]
Have we done this? part of me thinks someone did but I can't find it.

**Comment by Maschette** [comment]
Done in https://github.com/AustralianAntarcticDivision/SOmap/commit/a7cd6f5c43d33177c85d5df6504f545501fa4a93
