### ISSUE TITLE
SOmap_auto doesn't function properly

### ISSUE THREAD

**Issue by janjansen86** [AustralianAntarcticDivision/SOmap#76]
**Describe the bug**
SOmap_auto shows twisted plot when using the standard example given on the github page. Additionally, tracks/points somehow only show up when I specify par(mfrow=c(1,1)) before plotting. When I repeat the plotting command thereafter the tracks disappear again, only to show up again when I first do par(mfrow=c(1,1)). Something is very odd

**To Reproduce**
library(SOmap)
ellie <- SOmap_data$mirounga_leonina
par(mfrow=c(1,1))
SOmap_auto(ellie$lon, ellie$lat)

**Screenshots**
![Capture_so](https://user-images.githubusercontent.com/17172172/82957988-a7d95c80-9ff7-11ea-9205-570b7301da45.JPG)

**Desktop (please complete the following information):**
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SOmap_0.5.2.9999 raster_3.1-5     sp_1.4-2        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6       pillar_1.4.4       compiler_4.0.0     magic_1.5-9       
 [5] class_7.3-16       tools_4.0.0        lifecycle_0.2.0    tibble_3.0.1      
 [9] gtable_0.3.0       lattice_0.20-41    png_0.1-7          pkgconfig_2.0.3   
[13] rlang_0.4.6        cli_2.0.2          DBI_1.1.0          rstudioapi_0.11   
[17] reproj_0.4.2       parallel_4.0.0     rgdal_1.4-8        e1071_1.7-3       
[21] dplyr_0.8.5        vctrs_0.3.0        classInt_0.4-3     grid_4.0.0        
[25] tidyselect_1.1.0   glue_1.4.1         sf_0.9-3           R6_2.4.1          
[29] fansi_0.4.1        ggplot2_3.3.0      purrr_0.3.4        magrittr_1.5      
[33] scales_1.1.1       codetools_0.2-16   stars_0.4-1        ellipsis_0.3.1    
[37] units_0.6-6        abind_1.4-5        assertthat_0.2.1   proj4_1.0-10      
[41] colorspace_1.4-1   quadmesh_0.4.5     spex_0.6.0         KernSmooth_2.23-16
[45] geometry_0.4.5     PROJ_0.1.6         munsell_0.5.0      lwgeom_0.2-4      
[49] crayon_1.3.4

**Comment by Maschette** [comment]
I just tested this in a fresh install of R4.0.0 and get the same errors, the only two packages I can see that have been updated from my working version in R3.6.3 is raster and sp have both had updates. I assume it is something in those but I will have to check. Any suggestions @mdsumner?

**Comment by Maschette** [comment]
So running sessions in 3.6.3 and 4.0.0: 
4.0.0:
```
>SOmap:::mid_point(ellie[,4:5]) 
#           x_      y_
[1,] 80.51967  0

```
3.6.3:
```
> SOmap:::mid_point(ellie[,4:5])
           x_        y_
[1,] 80.51967 -67.77774
```

My assumption is this is then messing with automap_maker.

**Comment by Maschette** [comment]
So within the mid_point function if we do the individual steps it is the outside reproj that is dropping Y

``` r
library(SOmap)
#> Loading required package: raster
#> Loading required package: sp
p<-SOmap_data$mirounga_leonina[,4:5]

mid_point <- function (p, fold = FALSE)
{
  gc <- "+proj=geocent +datum=WGS84"
  lc <- "+proj=longlat +datum=WGS84"
  reproj::reproj(matrix(colMeans(reproj::reproj(p, target = gc, source  = lc), na.rm = TRUE), 1L),target = lc, source = gc)[1L, 1:2, drop = FALSE]
  
}

gc <- "+proj=geocent +datum=WGS84"
lc <- "+proj=longlat +datum=WGS84"

colMeans(reproj::reproj(p, target = gc, source  = lc), na.rm = TRUE)
#>        x_        y_        z_ 
#>  385044.9 2305801.0       0.0

matrix(colMeans(reproj::reproj(p, target = gc, source  = lc), na.rm = TRUE), 1L)
#>          [,1]    [,2] [,3]
#> [1,] 385044.9 2305801    0

reproj::reproj(matrix(colMeans(reproj::reproj(p, target = gc, source  = lc), na.rm = TRUE), 1L),target = lc, source = gc)[1L, 1:2, drop = FALSE]
#>            x_ y_
#> [1,] 80.51967  0
```

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment]
ah, indeed - understood  I know what that is, I need to explore a bit for the fix

**Comment by mdsumner** [comment]
@Maschette I think it's fixable by installing dev PROJ package, can you try?  (fixed on 21st April, *after* the mid April release sadly)

```R
remotes::install_github("hypertidy/PROJ")
```

If it does fix this I'll push a release soon, but we could put this in DESCRIPTION and require > CRAN version/s for SOmap (but if it's more complicated I could modify SOmap itself to do this with pure math). 

```
Remotes: hypertidy/PROJ, hypertidy/reproj
```

might need reproj as well (for good measure)

```R
remotes::install_github("hypertidy/reproj")
```

**Comment by Maschette** [comment]
Aside from the github PROJ install being a huge pain in the ass that seems to have fixed it.

**Comment by mdsumner** [comment]
a pain on windows? It probably needs a fresh R session, but I guess you found out

**Comment by Maschette** [comment]
A combination of needing to update rtools and for some reason not having write access for installing it into the library. 

So is the status of this now that @janjansen86 just needs to update PROJ and reproj?

**Comment by mdsumner** [comment]
yeah I just updated to SOmap to require these later vesions

@janjansen86 if you are on a server let me know and I'll update the system there
