### ISSUE TITLE
Wanted: Add EEZs to SOmap Data

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#78]
There is a selection of EEZs in SOmap at the moment but there are a number missing. it may be worth adding all the southern hemisphere EEZs?

**Comment by raymondben** [comment]
Noting here that Bouvet no longer appears, because it's no longer in the marineregions EEZ data. It has been moved into the territorial sea dataset: https://www.marineregions.org/gazetteer.php?p=details&id=8399
