### ISSUE TITLE
Version 0.6

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#80]
Just wondering what we are waiting on with version 0.6 to bring it into master? Some people have been given it to use, others haven't and it makes it a pain to keep track of with dealing with issues. 

If there is nothing major to be done I say we merge it across.

**Comment by mdsumner** [comment]
fine by me

**Comment by raymondben** [comment]
As far as I'm aware it's fine, but I think we would be wise to test thoroughly. @Maschette @mdsumner can you give it a hammer and ask any other regular users to do the same (just re-running existing code on it would be helpful)

**Comment by raymondben** [comment]
All right, here's what I think needs doing before 0.6 can become master:
[ ] @mdsumner to fix https://github.com/AustralianAntarcticDivision/SOmap/issues/86
[ ] update NEWS
[ ] someone figure out why on earth the first few maps in the README are aligned too far left and chopped off??
[ ] more testing

**Comment by Maschette** [comment]
So, given we have resolved the warnings, raster has been updated and everything seems to be passing, should we merge dev into master?

**Comment by raymondben** [comment]
All-but-one boxes ticked above - @Maschette you get to merge dev-0.6 into master and we can tick the last one ...

**Comment by Maschette** [comment]
:star: :star: :star: Done :star: :star: :star:
