### ISSUE TITLE
SOgg in dev-06 

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/SOmap#84]
I will post a full reprex with the error codes when I finish very gentleR but the dev-06 version is throwing an error with: 

```
myplot <- SOmap()
myplotgg <- SOgg(myplot) 
```
I think it is something to do with how it does the bathymetry legend. The master branch works fine, any thoughts @raymondben?

**Comment by raymondben** [comment]
I think we are all good. Made various small additional fixes that should improve visual consistency between the non-gg and gg version of a map.
