### ISSUE TITLE
SOproj doesn't work properly with graticules

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#86]
```
set.seed(1)
amap <- SOmap_auto(input_points = FALSE, input_lines = FALSE)
prj <- "+proj=laea +lat_0=-90 +lon_0=147 +datum=WGS84"
chk <- SOproj(amap, target = prj)
```

Look at `amap$graticule[[1]]$plotargs$x` and then its reprojected equivalent `chk$graticule[[1]]$plotargs$x`. The geometry has been reprojected, but the `x_start`, `y_start`, `x_end`, `y_end` columns have not - and these columns are used in `plot_graticule` (in SOmap_auto.R) to plot the graticule. Hence the last example in the README the graticules are out of whack with the rest of the plot.
I think those columns just need reprojecting. The `angle_start` and `angle_end` columns will be more problematic, because I don't see an obvious way to know automatically how to modify them to the new projection. But maybe you know ...

**Comment by mdsumner** [comment]
oh dang, good catch!

**Comment by mdsumner** [comment]
it'll probably need to be recreated because while the start and ends will be ok the angles will not (maybe that's ok, just something to wear ...) - otherwise we could recreate the graticule based on the new target

**Comment by mdsumner** [comment]
Reprojecting is going ok, but that plot setup problem  (the extent) is coming from somewhere else so haven't figured out yet

**Comment by mdsumner** [comment]
it's the `$init` was excluded from reproj

**Comment by mdsumner** [comment]
s'better now
