### ISSUE TITLE
reproj complaint

### ISSUE THREAD

**Issue by raymondben** [AustralianAntarcticDivision/SOmap#88]
```
x <- SOmap_auto(c(100:110), c(-70:-60))
 Error in PROJ::proj_trans_generic(x, target = target, ..., source = source) : 
  REAL() can only be applied to a 'numeric', not a 'integer' 
```
I think this is actually in reproj?

**Comment by mdsumner** [comment]
Yikes, nice one caught me out!  It might be enough to install PROJ and reproj from CRAN, but they are due an update

**Comment by raymondben** [comment]
Thanks - yup, seems to be fine with pkg updates (reproj 0.4.2, PROJ 0.1.6)
