### ISSUE TITLE
SOplot type not working

### ISSUE THREAD

**Issue by jessm93** [AustralianAntarcticDivision/SOmap#95]
When using SOplot, unless it is a raster it defaults to being a point using the `points()` function

https://github.com/AustralianAntarcticDivision/SOmap/blob/062bb0f18f89ce1fac6953404397a4301269af57/R/SOplot.R#L32

This means you cant plot with a line by setting `type=` if you changed that to plot than it should be able to take a type argument.

**Comment by Maschette** [comment]
This should be fixed now by changing that line to  `plot(SObj, add = TRUE,  ...) `
